# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Zynq/SDK/EMIO/EMIO.srcs/sources_1/bd/EMIO/ip/EMIO_processing_system7_0_0/EMIO_processing_system7_0_0.xci
# IP: The module: 'EMIO_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Zynq/SDK/EMIO/EMIO.srcs/sources_1/bd/EMIO/ip/EMIO_processing_system7_0_0/EMIO_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMIO_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/Zynq/SDK/EMIO/EMIO.srcs/sources_1/bd/EMIO/ip/EMIO_processing_system7_0_0/EMIO_processing_system7_0_0.xci
# IP: The module: 'EMIO_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Zynq/SDK/EMIO/EMIO.srcs/sources_1/bd/EMIO/ip/EMIO_processing_system7_0_0/EMIO_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'EMIO_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
