set_property SRC_FILE_INFO {cfile:E:/Zynq/SDK/EMIO/EMIO.srcs/constrs_1/new/EMIO.xdc rfile:../../../EMIO.srcs/constrs_1/new/EMIO.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports {EMIO_tri_io[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports {EMIO_tri_io[1]}]
