# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/EMIO.xdc

# Block Designs: bd/EMIO/EMIO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EMIO || ORIG_REF_NAME==EMIO} -quiet] -quiet

# IP: bd/EMIO/ip/EMIO_processing_system7_0_0/EMIO_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==EMIO_processing_system7_0_0 || ORIG_REF_NAME==EMIO_processing_system7_0_0} -quiet] -quiet

# XDC: bd/EMIO/EMIO_ooc.xdc
